version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    image: bang13/foodgram_backend
    restart: always
    command: gunicorn api_foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
