version: '3.7'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: bang13/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend/static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: bang13/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

  migrations:
    image: bang13/foodgram_backend
    volumes:
      - .:/backend/foodgram/
    command: bash -c "python manage.py makemigrations users --noinput &&
             python manage.py makemigrations recipes --noinput &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py loaddata static/data/ingredients.json"
    env_file:
      - ./.env
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_value:
  media_value:
