# Generated by Django 2.2.16 on 2022-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'guest'), ('user', 'user'), ('admin', 'admin')], max_length=100),
        ),
    ]
